Epoch 0:
	train loss:3434485.3504  val ap:0.957104  val auc:0.953486
	total time:1085.58s sample time:4.55s prep time:936.14s
Epoch 1:
	train loss:2969799.2834  val ap:0.960805  val auc:0.957372
	total time:1091.57s sample time:4.55s prep time:942.51s
Loading model at epoch 0...
Traceback (most recent call last):
  File "/raid/guorui/workspace/dgnn/a-tgl/train.py", line 246, in <module>
    model.load_state_dict(torch.load(path_saver))
  File "/raid/guorui/anaconda3/envs/sgnn/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/raid/guorui/anaconda3/envs/sgnn/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/raid/guorui/anaconda3/envs/sgnn/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/TALK_1721919248.826558.pkl'
