Epoch 0:
	train loss:967121.2419  val ap:0.736260  val auc:0.784355
	total time:335.01s sample time:1.27s prep time:289.67s
Epoch 1:
	train loss:797179.0446  val ap:0.764888  val auc:0.805355
	total time:328.44s sample time:1.24s prep time:289.31s
Loading model at epoch 0...
Traceback (most recent call last):
  File "/home/guorui/workspace/dgnn/a-tgl/train.py", line 246, in <module>
    model.load_state_dict(torch.load(path_saver))
  File "/home/guorui/anaconda3/envs/sgnn/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/guorui/anaconda3/envs/sgnn/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/guorui/anaconda3/envs/sgnn/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/LASTFM_1721917468.1747103.pkl'
